### ISSUE TITLE
Sherlock 2.4.2 cannot load projects from the packaged extension

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sherlock#224]
## Summary

Sherlock 2.4.2 cannot load any Inlang project after the upgrade from @inlang/sdk 2.10.2 to 3.0.1. The same project loads in 2.4.1 and in a development checkout, but fails from the packaged extension.

## Minimal reproduction

1. Package the current main branch:
   ```sh
   pnpm install
   pnpm exec vsce package --no-dependencies
   ```
2. Install the generated VSIX in VS Code.
3. Open `examples/minimal`, which contains the repository's minimal valid `project.inlang` fixture.

Alternatively, bundle a script that only calls `loadProjectFromDirectory()` with Sherlock's esbuild settings, move that bundle to an empty directory, and run it against `examples/minimal/project.inlang`.

## Actual result

The packaged extension cannot open the project. The isolated loader fails because the SDK 3 Lix runtime expects files that are not emitted beside Sherlock's single-file bundle. In the CommonJS extension build, esbuild also rewrites `import.meta` in the native binding loader, so `createRequire(import.meta.url)` receives `undefined`. If native loading is bypassed, the worker path then fails with:

```
Cannot find module '/tmp/.../entry.node.js'
```

The VSIX excludes `node_modules` and contains neither the platform-native Lix package nor the Node worker entry beside `dist/main.cjs`. The only Lix WASM in the archive belongs to the editor webview at a different path.

## Expected result

The packaged extension loads the minimal project, as Sherlock 2.4.1 does.

## Regression range

- Works: 2.4.1 (@inlang/sdk 2.10.2)
- Broken: 2.4.2 (@inlang/sdk 3.0.1)

## Proposed patch

Revert the SDK 3/editor/matcher dependency upgrade for the next patch release, and add an isolated-bundle regression test. A future SDK 3 upgrade needs an explicit Sherlock packaging strategy for the Lix native/worker/WASM runtime files.

**Comment by samuelstroschein** [comment]
Confirmed against the actually published Open VSX 2.4.2 artifact (`ovsx get inlang.vs-code-extension 2.4.2`), not only a local package. It has the same missing runtime signature and fails on `examples/minimal` with `ERR_INVALID_ARG_VALUE` from `createRequire(undefined)`.

**Comment by samuelstroschein** [comment]
The minimal reproduction and fix are now available:

- Sherlock SDK 3 packaging fix: https://github.com/opral/sherlock/pull/225
- upstream Lix worker fix: https://github.com/opral/lix/pull/1553

The final fix keeps SDK 3. Sherlock now packages as ESM on VS Code 1.100+, emits the Lix worker as a separate entry, and ships the worker's WASM fallback. The remaining VSIX-only failure came from VS Code's `--expose-gc` host flag: Node rejects that argument when forwarded to a worker with `ERR_WORKER_INVALID_EXEC_ARGV`. The Lix PR filters `--expose-gc` and `--input-type` while preserving host permission flags; Sherlock carries the same small pnpm patch until that fix is released.

Validated with 276 unit tests and two lifecycle tests against a freshly extracted VSIX.
